DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS platforms;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS groups;
DROP TABLE IF EXISTS letters;
DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS vacancies;
