version: '3.8'

services:
  postgres:
    build:
      context: ../..
      dockerfile: deployments/docker/postgres/Dockerfile
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - psql_vol:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: database_admin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@example.org
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - 80:80
    volumes:
      - pgadmin_vol:/var/lib/pgadmin:rw
    links:
      - postgres

  redis:
    image: library/redis
    container_name: session
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_vol:/data:rw

volumes:
    psql_vol:
    pgadmin_vol:
    redis_vol:
